In [3]:
import numpy as np

In [101]:
"""
NumPy Array Attributes
"""

# Creating an array

print(np.arange(3))
print(np.arange(3, 9))
print(np.arange(3, 9, 2))
print(np.arange(1, 11, 2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]
[1 3 5 7 9]


In [506]:
# Random number generator

np.random.seed(10)

arr1 = np.random.randint(10, size=6)
print(arr1)

arr2 = np.random.randint(10, size=(3, 4))
print(arr2)

arr3 = np.random.randint(10, size=(3, 4, 5))
print(arr3)

[9 4 0 1 9 0]
[[1 8 9 0]
 [8 6 4 3]
 [0 4 6 8]]
[[[1 8 4 1 3]
  [6 5 3 9 6]
  [9 1 9 4 2]
  [6 7 8 8 9]]

 [[2 0 6 7 8]
  [1 7 1 4 0]
  [8 5 4 7 8]
  [8 2 6 2 8]]

 [[8 6 6 5 6]
  [0 0 6 9 1]
  [8 9 1 2 8]
  [9 9 5 0 2]]]


In [67]:
# Attributes

print(arr2)

print("arr2.ndim = ", arr2.ndim)
print("arr2.ndim = ", arr2.shape) # 중요 #
print("arr2.ndim = ", arr2.size) # 중요 #

print("arr2.ndim = ", arr2.dtype) # 중요 #
print("arr2.ndim = ", arr2.itemsize)
print("arr2.ndim = ", arr2.nbytes)

[[3 2 4 9]
 [7 4 9 4]
 [1 2 7 2]]
arr2.ndim =  2
arr2.ndim =  (3, 4)
arr2.ndim =  12
arr2.ndim =  int32
arr2.ndim =  4
arr2.ndim =  48


In [515]:
"""
Slicing
"""

arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[0 2 4 6]


In [74]:
# Multi-dimensional subarrays

np.random.seed(0)
arr = np.random.randint(10, size=(6, 8))
print(arr)

arr_sub = arr[3:5, 4:7]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0 2]
 [3 7 0]]


In [519]:
"""
Subarrays as no-copy views
"""
np.random.seed(1)
arr = np.random.randint(10, size=(3,4))
print(arr, '\n')

arr_sub = arr[:2, :2]
print(arr_sub, '\n')

arr_sub[0,0] = 99
print(arr_sub, '\n')
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[99  8]
 [ 0  0]] 

[[99  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [535]:
# .copy()

np.random.seed(2)
arr = np.random.randint(10, size=(3, 4))
print(arr,'\n')

arr_sub = arr[:2, :2].copy()
print(arr_sub, '\n')

arr_sub[0][0] = 99
print(arr)

[[8 8 6 2]
 [8 7 2 1]
 [5 4 4 5]] 

[[8 8]
 [8 7]] 

[[8 8 6 2]
 [8 7 2 1]
 [5 4 4 5]]


In [549]:
"""
Reshaping of Arrays
"""
arr = np.arange(1,10)
print(arr, '\n')

# reshape()
grid = arr.reshape(3,3)
print(grid, '\n')

grid_sub = arr.reshape(9,1)
print(grid_sub, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 



In [569]:
# np.newaxis

arr = np.array([1, 2, 3])
print(arr)
print("arr_ndim = ", arr.ndim) # 차원 개수
print("arr.shape = ", arr.shape, '\n') # 배열 차원 크기

arr_new = arr[np.newaxis, :] # R^1x3
print(arr_new)
print("arr_new.ndim = ", arr_new.ndim) # 차원 개수
print("arr_new.shape = ", arr_new.shape, '\n') # 배열 차원 크기

arr_new1 = arr[:, np.newaxis] # R^3x1
print(arr_new1)
print("arr_new1.ndim = ", arr_new1.ndim) # 차원 개수
print("arr_new1.shape = ", arr_new1.shape) # 배열 차원 크기

[1 2 3]
arr_ndim =  1
arr.shape =  (3,) 

[[1 2 3]]
arr_new.ndim =  2
arr_new.shape =  (1, 3) 

[[1]
 [2]
 [3]]
arr_new1.ndim =  2
arr_new1.shape =  (3, 1)


In [22]:
"""
Array Concatenation
"""
# np.concatenate, np.vstack(), np.hstack()
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_1, arr_2, arr_3 = np.split(arr, [3,6])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total, '\n')

arr_total = np.vstack([arr_1, arr_2, arr_3]) # vertical
print(arr_total, '\n')

arr_total = np.hstack([arr_1, arr_2, arr_3]) # horizontal
print(arr_total, '\n')


[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9] 



In [54]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])
arr_3 = np.array([[13, 14, 15], [16, 17, 18]])

arr_total = np.concatenate([arr_1, arr_2, arr_3], axis=1) # arr_1, arr_2, arr_3 -> size(2, 3)
                                                          # axis = 0 -> rows == 2, axis = 1 -> column == 3
print(arr_total)

# axis exam

np.random.seed(10)
array_dim2 = np.random.randint(10, size=(5, 3))
print(array)

np.sum(array, axis = 0)
np.sum(array, axis = 1)

array_dim3 = np.random.randint(10, size=(5, 3, 2))
print(array_dim3)



[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]
[[9 4 0]
 [1 9 0]
 [1 8 9]
 [0 8 6]
 [4 3 0]]
[[[4 6]
  [8 1]
  [8 4]]

 [[1 3]
  [6 5]
  [3 9]]

 [[6 9]
  [1 9]
  [4 2]]

 [[6 7]
  [8 8]
  [9 2]]

 [[0 6]
  [7 8]
  [1 7]]]


In [44]:
"""
Array Splitting
"""
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr, '\n')

arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
