In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [23]:
# Creating a NumPy Array
"""
list = [1, 2, 3, 4]
arr = np.array(list)
print(arr)
"""
list = [1.6, 2.3, 3.2, 4.6]
arr = np.array(list)
print(arr)


[1.6 2.3 3.2 4.6]


In [25]:
# .dtype attribute
print(arr.dtype)

float64


In [34]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
print(getsizeof(list)) # 56 -> 64: int + object meta info.

arr = np. array(list)
print(getsizeof(arr)) # 104 -> 108: int(4bytes)

216
184


In [39]:
"""
Operations with NumPy Arrays
"""
prices = [30, 25, 40, 20, 20, 35, 50, 35]

# With a lsit
new_prices = [price-5 for price in prices]
print(new_prices)

# With a ndarray
prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [83]:
"""
Exercise
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2, 0])

print(student_scores[:, -1]) # == student_scores[:, 4]

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [3]:
"""
Logical Operations with Arrays
"""

# masking
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

# select using logical operations
selected = a[a > 5] # 배열 a에서 a의 값이 5보다 큰 원소들의 집합을 구하라.
print(selected)

# combined logical operations / &
selected = a[(a > 6) | (a < 4)] 
print(selected)

selected = a[(a > 4) & (a < 8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [8]:
"""
Exercise: Goldilocks Porridge Festival
"""
porridge_temp = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])
print(porridge_temp)

cold = porridge_temp[porridge_temp < 60]
print(cold)

hot = porridge_temp[porridge_temp > 80]
print(hot)

just_right = porridge_temp[(porridge_temp >= 60) & (porridge_temp <= 80)]
print(just_right)

[79 65 50 63 56 90 85 98 79 51]
[50 56 51]
[90 85 98]
[79 65 63 79]
