In [2]:
import numpy as np

In [4]:
"""
Comparison: Loop vs ufuncs(vectorized)
"""

big_array= np.random.randint(1, 100, size=1000000)

# Looping on a big array

# jupyter magic function
%timeit compute_reciprocals(big_array)

NameError: name 'compute_reciprocals' is not defined

In [5]:
# Vectorized operations
%timeit 1 / big_array

2.95 ms ± 313 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)
print(arr1, arr2)

arr1 = arr1 - 2
print(arr1, arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3,5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [13]:
"""
UFuncs: Absolute Value
"""

x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

[2 1 0 1 2]


array([5., 5., 2., 1.])

In [21]:
"""
UFuncs: Trigonometric Functions
"""

theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x  = np.linspace(0, 100, 11)
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [26]:
"""
Ufuncs: Aggregation
"""

x = np.arange(1,5)
print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [29]:
# accumulate()
accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[ 1  3  6 10]
[ 1  2  6 24]


In [32]:
# Summing the values in an Array

np.random.seed(3)
arr = np.random.rand(1000000) # rand(), create 0~1 real numbers
print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015305


In [38]:
%timeit sum(arr)

87.3 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
%timeit np.sum(arr)

1.39 ms ± 22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [47]:
# Other Aggr. functions

print("max =", np.max(arr))
print("min =", np.min(arr))

print(np.any(arr>1))
print(np.all(arr>0)) # range [0, 1)

max = 0.9999996367889004
min = 1.5496004267534502e-06
False
True


In [ ]:
# Multi dimensional aggregates

np.random.seed(5)
arr = np.random.randint(10, size=(3, 4))

np.sum(arr, axis)